function(autoinstall TARGET DIRECTORY)
    set_target_properties(${TARGET} PROPERTIES RUNTIME_OUTPUT_DIRECTORY ${DIRECTORY})
    foreach(CONFIG ${CMAKE_CONFIGURATION_TYPES})
        string(TOUPPER ${CONFIG} CONFIG)
        set_target_properties(${TARGET} PROPERTIES RUNTIME_OUTPUT_DIRECTORY_${CONFIG} ${DIRECTORY})
    endforeach()
endfunction()
